CREATE TABLE FUNCION_LINEAL (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    X NUMBER(10,2),
    Y NUMBER(10,2),
    M NUMBER(10,2),
    B NUMBER(10,2),
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

COMMIT;

SELECT * FROM FUNCION_LINEAL;